workflow:
    - deploy

shared:
    image: ruby:2

jobs:
  main:
    steps:
      - bundle_install: bundle install
      - build: bundle exec jekyll build --source docs --destination _site

  deploy:
      steps:
          - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
          - bundle_install: bundle install
          - build: bundle exec jekyll build --source docs --destination _site
          - deploy: ./deploy.sh
      secrets:
          # Pushing tags to Git
          - GIT_KEY
